# Generated by Django 2.0 on 2020-03-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kilo Gram'), ('G', 'Gram'), ('Mg', 'Mille Gram'), ('T', 'Tonne')], default='KG', max_length=100, null=True),
        ),
    ]
