# Generated by Django 2.0 on 2020-03-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0005_auto_20200328_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('firm_name', models.CharField(max_length=100)),
                ('previous_code', models.CharField(blank=True, default='', max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField()),
                ('seller_type', models.CharField(blank=True, choices=[('D', 'Dalal'), ('F', 'Firm')], default='Firm', max_length=5, null=True)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100)),
                ('branch_address', models.CharField(blank=True, default='', max_length=100)),
                ('branch_city', models.CharField(blank=True, default='', max_length=20)),
                ('branch_country', models.CharField(blank=True, default='', max_length=20)),
                ('branch_pincode', models.CharField(blank=True, default='', max_length=20)),
                ('office_address', models.CharField(blank=True, default='', max_length=100)),
                ('office_city', models.CharField(blank=True, default='', max_length=20)),
                ('office_country', models.CharField(blank=True, default='', max_length=20)),
                ('office_pincode', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SellerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(blank=True, choices=[('D', 'Dalal'), ('F', 'Firm')], default='Firm', max_length=5, null=True)),
                ('item_sold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_item_sold', to='commodity.Item')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_seller', to='seller.Seller')),
            ],
        ),
    ]
