# Generated by Django 2.0 on 2020-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20200328_0322'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerhistory',
            name='item_sold',
        ),
        migrations.RemoveField(
            model_name='sellerhistory',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='items',
            field=models.ManyToManyField(to='commodity.Item'),
        ),
        migrations.DeleteModel(
            name='SellerHistory',
        ),
    ]
